-- require("core.plugin_config.vscode")
require("core.plugin_config.nvim-tree")
-- Theme
require("core.plugin_config.neosolarized")
require("core.plugin_config.treesitter")
require("core.plugin_config.autopairs")
require("core.plugin_config.bufferline")
require("core.plugin_config.cmp")
require("core.plugin_config.colorizer")
require("core.plugin_config.comment")
require("core.plugin_config.gitsings")
require("core.plugin_config.lsp-colors")
require("core.plugin_config.lualine")
require("core.plugin_config.telescope")
require("core.plugin_config.ts-autotag")
require("core.plugin_config.web-devicons")
require("core.plugin_config.lsp")
require("core.plugin_config.lspkind")
require("core.plugin_config.lspsaga")
-- require("core.plugin_config.prettier")
-- require("core.plugin_config.null-ls")
require("core.plugin_config.eslint")
require("core.plugin_config.formatter")
require("core.plugin_config.mason")
